spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/plantodo
    username: root
    password: pepper27913@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages, errors
  redis:
    host: redis
    port: 6379

logging.level:
  root: debug
  org.hibernate.SQL: debug
  springframework.web: debug